# Generated by Django 4.2.7 on 2026-09-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(choices=[('early_action', '提前申请'), ('early_decision', '提前决定'), ('round_1', '第一轮'), ('round_2', '第二轮'), ('round_3', '第三轮'), ('regular', '常规申请')], max_length=50, verbose_name='申请轮次')),
                ('deadline_date', models.DateField(verbose_name='截止日期')),
                ('decision_release_date', models.DateField(blank=True, null=True, verbose_name='结果公布日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '申请截止日期',
                'verbose_name_plural': '申请截止日期',
                'ordering': ['program', 'deadline_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='最低GPA要求')),
                ('min_ielts', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='最低雅思要求')),
                ('min_toefl', models.IntegerField(blank=True, null=True, verbose_name='最低托福要求')),
                ('min_gre', models.IntegerField(blank=True, null=True, verbose_name='最低GRE要求')),
                ('min_gmat', models.IntegerField(blank=True, null=True, verbose_name='最低GMAT要求')),
                ('work_experience_required', models.BooleanField(default=False, verbose_name='需要工作经验')),
                ('work_experience_years', models.IntegerField(blank=True, null=True, verbose_name='要求工作年限')),
                ('other_requirements', models.TextField(blank=True, verbose_name='其他要求')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '申请要求',
                'verbose_name_plural': '申请要求',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='专业名称')),
                ('degree_level', models.CharField(choices=[('bachelor', '本科'), ('master', '硕士'), ('phd', '博士')], max_length=20, verbose_name='学位层次')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='院系')),
                ('description', models.TextField(blank=True, verbose_name='专业简介')),
                ('duration_years', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='学制(年)')),
                ('tuition', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='学费')),
                ('language_of_instruction', models.CharField(default='英语', max_length=50, verbose_name='授课语言')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
                'ordering': ['university', 'name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='院校名称')),
                ('country', models.CharField(max_length=100, verbose_name='国家')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('qs_ranking', models.IntegerField(blank=True, null=True, verbose_name='QS排名')),
                ('times_ranking', models.IntegerField(blank=True, null=True, verbose_name='Times排名')),
                ('description', models.TextField(blank=True, verbose_name='院校简介')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/logos/', verbose_name='校徽')),
                ('website', models.URLField(blank=True, max_length=500, verbose_name='官网')),
                ('tuition_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='最低学费')),
                ('tuition_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='最高学费')),
                ('tuition_currency', models.CharField(default='USD', max_length=10, verbose_name='学费货币')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '院校',
                'verbose_name_plural': '院校',
                'ordering': ['qs_ranking', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='推荐理由')),
                ('match_score', models.IntegerField(blank=True, help_text='1-100分', null=True, verbose_name='匹配度评分')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='是否已查看')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '院校推荐',
                'verbose_name_plural': '院校推荐',
                'ordering': ['-created_at'],
            },
        ),
    ]
