# Generated by Django 4.2.7 on 2026-09-25 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='universityrecommendation',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='顾问'),
        ),
        migrations.AddField(
            model_name='universityrecommendation',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universities.program', verbose_name='推荐专业'),
        ),
        migrations.AddField(
            model_name='universityrecommendation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_received', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='universityrecommendation',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university', verbose_name='推荐院校'),
        ),
        migrations.AddField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university', verbose_name='所属院校'),
        ),
        migrations.AddField(
            model_name='applicationrequirement',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='universities.program', verbose_name='所属专业'),
        ),
        migrations.AddField(
            model_name='applicationdeadline',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='universities.program', verbose_name='所属专业'),
        ),
    ]
