# Generated by Django 4.2.7 on 2026-09-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planning', '规划中'), ('preparing', '准备材料'), ('submitted', '已提交'), ('waiting', '等待结果'), ('admitted', '已录取'), ('rejected', '已拒'), ('waitlisted', '候补'), ('deferred', '延期')], default='planning', max_length=20, verbose_name='申请状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('application_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='申请费')),
                ('fee_paid', models.BooleanField(default=False, verbose_name='申请费已缴纳')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('result_date', models.DateTimeField(blank=True, null=True, verbose_name='结果公布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '申请项目',
                'verbose_name_plural': '申请项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('planning', '规划中'), ('preparing', '准备材料'), ('submitted', '已提交'), ('waiting', '等待结果'), ('admitted', '已录取'), ('rejected', '已拒'), ('waitlisted', '候补'), ('deferred', '延期')], max_length=20, null=True, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('planning', '规划中'), ('preparing', '准备材料'), ('submitted', '已提交'), ('waiting', '等待结果'), ('admitted', '已录取'), ('rejected', '已拒'), ('waitlisted', '候补'), ('deferred', '延期')], max_length=20, verbose_name='新状态')),
                ('change_reason', models.TextField(blank=True, verbose_name='变更原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.applicationproject', verbose_name='申请项目')),
            ],
            options={
                'verbose_name': '状态变更记录',
                'verbose_name_plural': '状态变更记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
