# Generated by Django 4.2.7 on 2026-09-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ps', '个人陈述 (PS)'), ('rl', '推荐信 (RL)'), ('cv', '简历 (CV)'), ('essay', 'Essay'), ('other', '其他')], max_length=20, verbose_name='文书类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='文件')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文书',
                'verbose_name_plural': '文书',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('start_position', models.IntegerField(blank=True, null=True, verbose_name='起始位置')),
                ('end_position', models.IntegerField(blank=True, null=True, verbose_name='结束位置')),
                ('highlighted_text', models.TextField(blank=True, verbose_name='高亮文本')),
                ('status', models.CharField(choices=[('active', '生效中'), ('outdated', '待处理'), ('resolved', '已解决')], default='active', help_text='生效中=绑定最新稿；待处理=旧稿批注，需顾问重新绑定后才生效；已解决', max_length=20, verbose_name='状态')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已解决')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文书批注',
                'verbose_name_plural': '文书批注',
                'ordering': ['document', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='版本号')),
                ('content', models.TextField(verbose_name='正文内容')),
                ('file', models.FileField(blank=True, null=True, upload_to='document_versions/', verbose_name='文件附件')),
                ('word_count', models.IntegerField(default=0, verbose_name='字数')),
                ('change_note', models.TextField(blank=True, verbose_name='修改说明')),
                ('diff_from_previous', models.TextField(blank=True, verbose_name='与上一版本差异')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '文书版本',
                'verbose_name_plural': '文书版本',
                'ordering': ['document', '-version_number'],
            },
        ),
    ]
