# Generated by Django 4.2.7 on 2026-09-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('transcript', '成绩单'), ('language', '语言成绩'), ('certificate', '在读证明/学位证'), ('id', '身份证明'), ('financial', '财力证明'), ('other', '其他')], max_length=20, verbose_name='材料类型')),
                ('name', models.CharField(max_length=200, verbose_name='材料名称')),
                ('description', models.TextField(blank=True, verbose_name='材料说明')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必需')),
                ('countries', models.CharField(blank=True, help_text='多个国家用逗号分隔', max_length=200, verbose_name='适用国家')),
                ('degree_levels', models.CharField(blank=True, help_text='bachelor,master,phd', max_length=200, verbose_name='适用学位')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '材料模板',
                'verbose_name_plural': '材料模板',
                'ordering': ['material_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='材料名称')),
                ('material_type', models.CharField(choices=[('transcript', '成绩单'), ('language', '语言成绩'), ('certificate', '在读证明/学位证'), ('id', '身份证明'), ('financial', '财力证明'), ('other', '其他')], default='other', max_length=20, verbose_name='材料类型')),
                ('description', models.TextField(blank=True, verbose_name='材料说明')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必需')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='上传文件')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='上传时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='applications.applicationproject', verbose_name='所属申请项目')),
            ],
            options={
                'verbose_name': '申请材料',
                'verbose_name_plural': '申请材料',
                'ordering': ['application', '-is_required', 'material_type', 'name'],
            },
        ),
    ]
