# Generated by Django 4.2.7 on 2026-09-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', '邮件'), ('system', '站内消息'), ('sms', '短信')], default='system', max_length=20, verbose_name='通知类型')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=20, verbose_name='优先级')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('exam', '语言考试'), ('document', '文书截止'), ('application', '网申截止'), ('interview', '面试'), ('decision', '预计出结果'), ('custom', '自定义')], max_length=20, verbose_name='事件类型')),
                ('title', models.CharField(max_length=200, verbose_name='事件标题')),
                ('description', models.TextField(blank=True, verbose_name='事件描述')),
                ('event_date', models.DateTimeField(verbose_name='事件日期')),
                ('deadline_date', models.DateTimeField(blank=True, null=True, verbose_name='截止日期')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='提醒已发送')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='applications.applicationproject', verbose_name='所属申请项目')),
            ],
            options={
                'verbose_name': '时间线事件',
                'verbose_name_plural': '时间线事件',
                'ordering': ['application', 'event_date'],
            },
        ),
    ]
